server:
  port: 8080

spring:
  application:
    name: "muebles-sas"
  devtools:
    add-properties: false

  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null

aws:
  region: ${AWS_REGION:us-east-1}
  dynamodb:
    endpoint: ${AWS_DYNAMODB_ENDPOINT:http://localhost:8000}


management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

